// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTvP1E-q9SOAQSHKRQeLnt2ontIQ9YFGU',
    appId: '1:643750882754:web:b148b2db282efea39bfa5b',
    messagingSenderId: '643750882754',
    projectId: 'chatapp123-b3c8f',
    authDomain: 'chatapp123-b3c8f.firebaseapp.com',
    storageBucket: 'chatapp123-b3c8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ZPO3yM5RrwRycX35w2byzSnHVWeDPwQ',
    appId: '1:643750882754:android:0fe26a141a0d66469bfa5b',
    messagingSenderId: '643750882754',
    projectId: 'chatapp123-b3c8f',
    storageBucket: 'chatapp123-b3c8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvN-ZNSJbGbjlLDr48lw4-2r-2TxkXAV8',
    appId: '1:643750882754:ios:fa6a8cf21808f4549bfa5b',
    messagingSenderId: '643750882754',
    projectId: 'chatapp123-b3c8f',
    storageBucket: 'chatapp123-b3c8f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvN-ZNSJbGbjlLDr48lw4-2r-2TxkXAV8',
    appId: '1:643750882754:ios:fa6a8cf21808f4549bfa5b',
    messagingSenderId: '643750882754',
    projectId: 'chatapp123-b3c8f',
    storageBucket: 'chatapp123-b3c8f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTvP1E-q9SOAQSHKRQeLnt2ontIQ9YFGU',
    appId: '1:643750882754:web:92c58c8e23eb10479bfa5b',
    messagingSenderId: '643750882754',
    projectId: 'chatapp123-b3c8f',
    authDomain: 'chatapp123-b3c8f.firebaseapp.com',
    storageBucket: 'chatapp123-b3c8f.firebasestorage.app',
  );
}
